---
title: "scorecard_analysis"
author: "Sumitra, Jamie, and Naeem"
date: "October 8, 2019"
output: html_document
---

##Setup
### options
Set up global options

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70))
knitr::opts_chunk$set(fig.height=4, fig.width=6)
```


### libraries
Load in needed libraries 
```{r libraries}
# Run these if you don't have these libraries yet
# install.packages("tidyverse") 
# install.packages("data.table")
library(tidyverse) # For data processing and visualization
library(data.table) # For creating tables

spot_color = "#9ecae1" 
text_color = "#525252"
```

### File management
Create variables for directories
```{r file_management}
home.dir <- getwd()
data.dir <- '../CollegeScorecard_Raw_Data'
output.dir <- '../outputs'
```

## Preprocessing
### import
This chunk will eventually read in data for all years. Will get completed after we've settled on subsets. 
__TO DO__
- coerce needed columns to correct data type
```{r preprocessing}
import_all <- function() {
    list.files(pattern = "*.csv") %>% 
    map_df(~read_csv(., na = c("NULL")))
}
```

### Test Import for small dataset
```{r}
scorecard_17 <- read_csv(file.path(home.dir, data.dir, "MERGED2017_18_PP.csv"), na = c("NULL", "PrivacySuppressed"))
```

### Quality Measurements
```{r}
# What is the proportion of nulls in the MD_EARN_WNE_P10 column?
length(scorecard_17$MD_EARN_WNE_P10[scorecard_17$MD_EARN_WNE_P10 == 'NULL']) /nrow(scorecard_17)

# Since the proportion of nulls is 1, all of the rows in the column are NULL.
```

